# Generated by Django 5.0.3 on 2024-04-02 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Candidato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cpf", models.CharField(max_length=11)),
                ("nome", models.CharField(max_length=50)),
                ("email", models.CharField(max_length=50)),
                ("area_atuacao", models.CharField(max_length=50)),
                ("descricao", models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Habilidades",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("habilidade", models.CharField(max_length=50)),
                (
                    "candidato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.candidato"
                    ),
                ),
            ],
        ),
    ]
