# Generated by Django 5.0.3 on 2024-04-04 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Empresa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cnpj", models.CharField(max_length=14, unique=True)),
                ("nome_fantasia", models.CharField(max_length=50)),
                ("ramo_empresarial", models.CharField(max_length=50)),
                ("cidade", models.CharField(max_length=100)),
                ("descricao", models.TextField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Recrutador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
            ],
            options={
                "verbose_name_plural": "Recrutadores",
            },
        ),
        migrations.AlterModelOptions(
            name="habilidades",
            options={"verbose_name_plural": "Habilidades"},
        ),
        migrations.CreateModel(
            name="Vaga",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                ("area", models.CharField(max_length=50)),
                (
                    "salario",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("requisitos", models.TextField(max_length=255)),
                ("descricao", models.TextField(max_length=255)),
                (
                    "recrutador",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="main.recrutador",
                    ),
                ),
            ],
        ),
    ]
